import type { Metadata } from 'next';
import { Playfair } from 'next/font/google';

import './globals.css';

const playfair = Playfair({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'PSONetto Portfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: any;
}) {
  return (
    <html lang={params.lang}>
      <body className={playfair.className}>{children}</body>
    </html>
  );
}
